namespace FileNameCleaner
{
    public static class Helpers
    {
        public static string RemoveOtherWords(string original)
        {
            List<string> words = new()
    {
        "[2160p-dv hdr10plus.EAC3 Atmos-en,EAC3-es.Subs-es,en]",
        "EXTENDED.720p.BluRay.999MB.HQ.x265.10bit-GalaxyRG",
        "-DL.DDP5.1.Atmos.H.264-FLUX.[TheRostrum.net]",
        "10bit Rip 6CH HEVC x265-FLUX [psarips]",
        "10bit Rip 6CH HEVC x265-NTb [psarips]",
        "p.AMZN.WEBRip.800MB.x264-GalaxyRG",
        "DNSP Rip AAC5 1 10bits x265-Rapta",
        "BRip.x264-XEN0N.[TheRostrum.net]",
        "AMZN.WEBRip.800MB.x264-GalaxyRG",
        "p.AMZN.WEB-DL.DDP5.1.H.264-FLUX",
        "p.AMZN.WEB-DL.DDP5.1.H.264-NTb.",
        "p h264 Ac3 Dual Subs][GrupoTS]",
        "1080p.BrRip.x264.BOKIUTOX.YIFY",
        ".DVDRip.x264.by.InI.no.dialogs",
        "DVDRip.x264.by.InI.no.dialog",
        "VOSTFR Rip x264-Wawacity rsvp",
        "Rip x264-TVSmash [tvu org ru]",
        "1080p HEVC -MeGusta[EZTVx to]",
        "BDRIP.4K.576p.x264.AC3.KJNU",
        "Eng Esp Dvdrip Divx-Elzeta",
        "HEVC x265-MeGusta[EZTVx to]",
        "HEVC.x265-MeGusta[EZTVx.to]",
        "WEB-DL.DD+5.1.H.264-playWEB",
        "HornedSplendidPuduOfFocus",
        "H 264 Multisubs MortFurd",
        ".NF.WEBRip.x264-GalaxyTV",
        "1080p Rip 6CH HEVC [psas]",
        "DVDRip DivX 5 0 2 Wrist",
        "MULTi HDR DV 2160p -FW",
        "1080p -ELiTE[EZTVx to]",
        ".DVDRip.XviD-ALLiANCE",
        "x265-ELiTE[EZTVx to]",
        "HDR 2160p h265-ETHEL",
        "P Av1 10Bit-Megusta",
        "DVDRip.x264-HANDJOB",
        "[sharethefiles.com]",
        "P Hevc x265-Megusta",
        "x264-TORRENTGALAXY",
        "BDRip -SPARKS _arc",
        "RE-ENCODE Rip -NTb",
        "Rip AAC5 1-[YTS MX]",
        "Rip.x264-GalaxyTV",
        "-GloriousMongoose",
        "HEVC x265 MeGusta",
        "Rip x264-GalaxyTV",
        "by.InI.no.dialogs",
        "Atmos.H.264-FLUX",
        ".UNRATED.EDITION",
        "DVDrip.no.dialog",
        "Atmos H 264-FLUX",

        "[TheRostrum.net]",
        "[ Dual][GrupoTS]",
        "Filmaffinity 5,8",
        "[VHSRip (XVID)]",
        "Bdrip h264-Rbb",
        "BDRip -Replica",
        "-mSD[EZTVx.to]",
        "SNAKE[EZTVx.to]",
        "Eng, Esp-Divx5",
        "SuccessfulCrab",
        "Rip.x264-RARBG",
        "HDTV x264-FoV",
        "Eng Esp Dvdrip",
        "H264-LAZYCUNTS",
        "H264-DiMEPiECE",
        "RGzsRutracker",
        "PDTV XviD-FTP",
        "PDTV XviD-FTP",
        "HDTV x264-MTB",
        "XviD.AC3-EVO",
        "H264-sexylegs",
        "x264-Wawacity",
        "[MULTI-AUDIO]",
        "DDP5.1.H.264",
        "Divx-Elzeta",
        "264-Kitsune",
        "H264-METCON",
        "-icecracked",
        "HDR 2160p -",
        ".h264-DIANA",
        "[tvu.org.ru]",
        "BDRip -ROEN",
        "AMZN.WEBRip",
        "h264-EDITH",
        "SYLiX LiTE",
        "x264-ION10",
        "XviD-Rogue",
        "XviD AGENT",
        "H264-CAKES",
        "x264-FENiX",
        "h264-ETHEL",
        "(Xvid-Eng)",
        "x264-River",
        "THEATRICAL",
        "h264-KOGi",
        "H264-GGEZ",
        "H 264-NTb",
        "[psarips]",
        "h264-glhf",
        "x265-FLUX",
        "BOKIUTOX",
        "6CH.HEVC",
        "Atmos H",
        "[ENG]",
        "[FXG]",
        "MARS",
        "V O S  Spa-Eng",
        "XviD-Eng",
        "iNTERNAL",
        "[YTS.MX]",
        "Xvid-Sfm",
        "Xvid-Bia",
        "[YTS AM]",
        "GalaxyRG",
        "264-NTb",
        "MiMESiS",
        "-KNiVES",
        "-ELiTE",
        "WEB-DL",
        "AAC2.0",
        "DVDRip",
        "Subita",
        "800MB",
        "BluRay",
        "DDP5.1",
        "p.AMZN",
        "10bit",
        "WEB-DL",
        "DUBBED",
        "-NHTFS",
        "-MANiC",
        "Webrip",
        "VOSTFR",
        "WEBRip",
        "Dvdrip",
        "WEB-DL",
        "DDP5.1",
        "Insert",
        "DLRip",
        "SYLiX",
        "BDRip",
        "MANiC",
        "BrRip",
        "999MB",
        "10bit",
        "CAKES",
        "HDRip",
        "-CBFM",
        "DSNP",
        "VOSE",
        "bike",
        ".MAX",
        "AMZN",
        "-TVD",
        "H264",
        "x264",
        "H265",
        "x264",
        "-NTb",
        "FLUX",
        "VETO",
        "540p",
        "H264",
        "AMZN",
        "HDTV",
        "Hdtv",
        "x265",
        "YIFY",
        "Divx",
        "576p",
        "Aac-",
        "MAX",
        "RBB",
        "WEB",
        "rip",
        "rip",
        "-aXXo",
        "DivX",
        "[Eng]",
        "rip",
        "-DL",
        "DL-",
        " -",
        "DL",
        "HQ",
        "()"
    };

            words = words.OrderByDescending(x => x.Length).ToList();

            foreach (var word in words)
            {
                if (!string.IsNullOrWhiteSpace(word))
                    original = original.Replace(word, "");
            }

            original = original.Replace("..", ".");
            original = original.Replace("..", ".");
            original = original.Replace("..", ".");
            original = original.Replace("..", ".");
            original = original.Replace(".", " ");
            return original.Trim();
        }
    }
}